### ISSUE TITLE
NullPointerException when syncing with a TaskServer

### ISSUE THREAD

**Issue by emembrives** [MirakelX/mirakel-android#616] opened 2016-01-13 19:03 UTC
I get the following error when trying to sync with a Taskwarrior server (taken using Android built-in bug reporting tool):
```
01-13 19:48:28.961 31776 31794 E ACRA    : ACRA caught a NullPointerException for de.azapps.mirakelandroid
01-13 19:48:28.961 31776 31794 E ACRA    : java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.database.sqlite.SQLiteDatabase.inTransaction()' on a null object reference
01-13 19:48:28.961 31776 31794 E ACRA    : 	at de.azapps.mirakel.model.MirakelInternalContentProvider.withTransaction(MirakelInternalContentProvider.java:441)
01-13 19:48:28.961 31776 31794 E ACRA    : 	at de.azapps.mirakel.model.list.ListMirakel.create(ListMirakel.java:404)
01-13 19:48:28.961 31776 31794 E ACRA    : 	at de.azapps.mirakel.model.list.ListMirakel.newList(ListMirakel.java:369)
01-13 19:48:28.961 31776 31794 E ACRA    : 	at de.azapps.mirakel.sync.taskwarrior.TaskWarriorSync.createProjects(TaskWarriorSync.java:470)
01-13 19:48:28.961 31776 31794 E ACRA    : 	at de.azapps.mirakel.sync.taskwarrior.TaskWarriorSync.doSync(TaskWarriorSync.java:167)
01-13 19:48:28.961 31776 31794 E ACRA    : 	at de.azapps.mirakel.sync.taskwarrior.TaskWarriorSync.sync(TaskWarriorSync.java:554)
01-13 19:48:28.961 31776 31794 E ACRA    : 	at de.azapps.mirakel.sync.taskwarrior.TaskWarriorSync.doSync(TaskWarriorSync.java:127)
01-13 19:48:28.961 31776 31794 E ACRA    : 	at de.azapps.mirakel.sync.taskwarrior.TaskWarriorSync.sync(TaskWarriorSync.java:554)
01-13 19:48:28.961 31776 31794 E ACRA    : 	at de.azapps.mirakel.sync.taskwarrior.services.SyncAdapter.onPerformSync(SyncAdapter.java:116)
01-13 19:48:28.961 31776 31794 E ACRA    : 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
```
Thanks!

**Comment by weiznich** [comment] 2016-01-13 22:02
Duplicate of #601

**Closed by weiznich** 2016-01-13 22:02 UTC
Labels: bug, duplicate, Taskwarrior
